const EXAM=new Date('2027-02-16T08:00:00'); const KEY='fe_vocab_progress_v1', SETKEY='fe_vocab_settings_v1';
let vocab=[], queue=[], idx=0, mode='';
let progress=JSON.parse(localStorage.getItem(KEY)||'{}'); let settings=Object.assign({rate:.75,newLimit:25},JSON.parse(localStorage.getItem(SETKEY)||'{}'));
const $=id=>document.getElementById(id), today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(progress));localStorage.setItem(SETKEY,JSON.stringify(settings));stats()}
function p(id){return progress[id]||{reviews:0,interval:0,due:'',last:'',strength:0}}
function days(n){let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function stats(){let vals=Object.values(progress);$('learnedCount').textContent=vals.filter(x=>x.reviews>0).length;$('masteredCount').textContent=vals.filter(x=>x.interval>=14).length;$('dueCount').textContent=vocab.filter(v=>p(v.id).reviews>0&&p(v.id).due<=today()).length}
function countdown(){let n=Math.max(0,Math.ceil((EXAM-new Date())/86400000));$('countdown').textContent=`${n} days to FE Other Disciplines · Feb 16, 2027`}
function orderNew(a,b){let rank={CORE_NOW:0,SUPPORT_NEXT:1,DEFER_OPTIONAL:2};return rank[a.pool]-rank[b.pool]||a.id-b.id}
function start(which){mode=which;let due=vocab.filter(v=>p(v.id).reviews>0&&p(v.id).due<=today());if(which==='morning'){let fresh=vocab.filter(v=>p(v.id).reviews===0).sort(orderNew).slice(0,settings.newLimit);queue=[...due,...fresh]}else{let seenToday=vocab.filter(v=>p(v.id).last===today());queue=[...new Map([...due,...seenToday].map(v=>[v.id,v])).values()]}
 idx=0;$('browse').classList.add('hidden');$('session').classList.remove('hidden');$('sessionTitle').textContent=which==='morning'?'Morning Session':'Afternoon Review';show()}
function show(){if(idx>=queue.length){$('sessionTitle').textContent='Session complete';$('sessionProgress').textContent=`${queue.length}/${queue.length}`;$('card').classList.add('hidden');$('ratings').classList.add('hidden');return} $('card').classList.remove('hidden');let v=queue[idx];$('sessionProgress').textContent=`${idx+1}/${queue.length}`;$('term').textContent=v.term;$('ipa').textContent=v.ipa;$('stress').textContent=v.stress?`Stress: ${v.stress}`:'';$('zh').textContent=v.zh;$('connection').textContent=v.connection;$('domain').textContent=v.domain;$('pool').textContent=v.pool.replace('_NOW','').replace('_NEXT','');$('source').textContent=`${v.source} · Handbook hits: ${v.hbHits}`;$('answer').classList.add('hidden');$('ratings').classList.add('hidden');$('revealBtn').classList.remove('hidden')}
function speak(){let v=queue[idx];if(!v)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(v.term);u.lang='en-US';u.rate=Number(settings.rate);let voices=speechSynthesis.getVoices();let voice=voices.find(x=>x.lang==='en-US')||voices.find(x=>x.lang.startsWith('en'));if(voice)u.voice=voice;speechSynthesis.speak(u)}
function grade(g){let v=queue[idx],x=p(v.id);x.reviews++;x.last=today();if(g==='again'){x.interval=0;x.due=today();x.strength=0}else if(g==='hard'){x.interval=Math.max(1,Math.round((x.interval||1)*1.2));x.due=days(x.interval);x.strength=1}else if(g==='good'){let seq=[1,3,7,14,30,60];x.interval=seq.find(n=>n>(x.interval||0))||90;x.due=days(x.interval);x.strength=2}else{x.interval=x.interval<3?3:x.interval<7?7:x.interval<14?14:x.interval<30?30:60;x.due=days(x.interval);x.strength=3}progress[v.id]=x;save();idx++;show()}
function browse(){ $('session').classList.add('hidden');$('browse').classList.remove('hidden');renderResults() }
function renderResults(){let q=$('search').value.trim().toLowerCase(),f=$('filter').value;let arr=vocab.filter(v=>(f==='ALL'||v.pool===f)&&(!q||v.term.toLowerCase().includes(q)||v.zh.includes(q))).slice(0,100);$('results').innerHTML=arr.map(v=>`<div class="result"><b>${v.term}</b> <span>${v.ipa}</span><small>${v.zh} · ${v.domain} · ${v.pool}</small></div>`).join('')||'<p>No matches.</p>'}
$('morningBtn').onclick=()=>start('morning');$('afternoonBtn').onclick=()=>start('afternoon');$('browseBtn').onclick=browse;$('revealBtn').onclick=()=>{$('answer').classList.remove('hidden');$('ratings').classList.remove('hidden');$('revealBtn').classList.add('hidden')};$('speakBtn').onclick=speak;document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(b.dataset.grade));$('endBtn').onclick=()=>{$('session').classList.add('hidden');$('card').classList.remove('hidden')};$('search').oninput=renderResults;$('filter').onchange=renderResults;
$('settingsBtn').onclick=()=>{$('rate').value=settings.rate;$('newLimit').value=settings.newLimit;$('settings').showModal()};$('closeSettings').onclick=()=>{settings.rate=Number($('rate').value);settings.newLimit=Number($('newLimit').value);$('speakBtn').textContent=`🔊 ${settings.rate}×`;save();$('settings').close()};
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),progress,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fe-vocab-progress.json';a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=async e=>{let j=JSON.parse(await e.target.files[0].text());if(j.progress){progress=j.progress;settings=Object.assign(settings,j.settings||{});save();alert('Progress imported.')}};$('resetBtn').onclick=()=>{if(confirm('Reset all study progress?')){progress={};save()}};
fetch('data/vocab.json').then(r=>r.json()).then(x=>{vocab=x;stats();countdown();$('speakBtn').textContent=`🔊 ${settings.rate}×`}).catch(()=>alert('Vocabulary data failed to load. This PWA must be served over HTTP/HTTPS, not opened as file://.'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
